name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:
  run_workspace_tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: xcodebuild test -scheme EssentialFeed -project EssentialFeed/EssentialFeed.xcodeproj
